// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD15OAHwTg16dTJB_RbS3vbyeT1oK2_Tzk',
    appId: '1:1073529717659:web:ada30d328558a055d8573e',
    messagingSenderId: '1073529717659',
    projectId: 'flutter-firebase-cli-5-pm',
    authDomain: 'flutter-firebase-cli-5-pm.firebaseapp.com',
    storageBucket: 'flutter-firebase-cli-5-pm.appspot.com',
    measurementId: 'G-QHPKXRV4S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyc9dcqpIAGj0e7vlh5iv-9Ckti5TZyU',
    appId: '1:1073529717659:android:85ce0e75cc0cd30ad8573e',
    messagingSenderId: '1073529717659',
    projectId: 'flutter-firebase-cli-5-pm',
    storageBucket: 'flutter-firebase-cli-5-pm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI58GYJT9iH6EwscCZxDvDGAujmYLJHAI',
    appId: '1:1073529717659:ios:34630570abf0a0a3d8573e',
    messagingSenderId: '1073529717659',
    projectId: 'flutter-firebase-cli-5-pm',
    storageBucket: 'flutter-firebase-cli-5-pm.appspot.com',
    iosClientId: '1073529717659-a516ldcrpr1n6h75kbhof3betluh1jfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCliProjectFivePm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI58GYJT9iH6EwscCZxDvDGAujmYLJHAI',
    appId: '1:1073529717659:ios:79aa8ab586c75dc3d8573e',
    messagingSenderId: '1073529717659',
    projectId: 'flutter-firebase-cli-5-pm',
    storageBucket: 'flutter-firebase-cli-5-pm.appspot.com',
    iosClientId: '1073529717659-ojeh48g79tcqs6ov9774ae81uegac178.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCliProjectFivePm.RunnerTests',
  );
}
